services:
  - type: web
    name: sportstore-api
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install --omit=dev && npm run prisma:generate && npx prisma migrate deploy --filter=backend && npm run build
    startCommand: npm run start --workspace backend
    envVars:
      - key: NODE_ENV
        value: production
